import os

POSTGRES_DB = os.getenv("POSTGRES_DB", "chat4all")
POSTGRES_USER = os.getenv("POSTGRES_USER", "chat4all")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD", "chat4all")
POSTGRES_HOST = os.getenv("POSTGRES_HOST", "postgres")
POSTGRES_PORT = int(os.getenv("POSTGRES_PORT", "5432"))

DATABASE_URL = (
    f"postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}"
    f"@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}"
)

KAFKA_BOOTSTRAP_SERVERS = os.getenv("KAFKA_BOOTSTRAP_SERVERS", "kafka:9092")
KAFKA_CHAT_TOPIC = os.getenv("KAFKA_CHAT_TOPIC", "chat-messages")

OBJECT_STORAGE_ENDPOINT = os.getenv("OBJECT_STORAGE_ENDPOINT", "minio:9000")
OBJECT_STORAGE_ACCESS_KEY = os.getenv("OBJECT_STORAGE_ACCESS_KEY", "chat4all")
OBJECT_STORAGE_SECRET_KEY = os.getenv("OBJECT_STORAGE_SECRET_KEY", "chat4all123")
OBJECT_STORAGE_BUCKET_NAME = os.getenv("OBJECT_STORAGE_BUCKET_NAME", "chat4all-files")
OBJECT_STORAGE_SECURE = os.getenv("OBJECT_STORAGE_SECURE", "0")
OBJECT_STORAGE_SECURE_BOOL = OBJECT_STORAGE_SECURE == "1"

# NOVO / IMPORTANTE: endpoint público, para gerar a URL que o navegador vai usar
OBJECT_STORAGE_PUBLIC_ENDPOINT = os.getenv("OBJECT_STORAGE_PUBLIC_ENDPOINT", "localhost:9000")